# Generated by Django 5.1.10 on 2025-06-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Module Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('app_name', models.CharField(max_length=100, unique=True, verbose_name='App Name')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('is_installed', models.BooleanField(default=False, verbose_name='Is Installed')),
                ('install_date', models.DateTimeField(blank=True, null=True, verbose_name='Install Date')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['name'],
            },
        ),
    ]
