# Generated by Django 5.1.10 on 2025-06-09 01:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_engine', '0002_module_created_module_modified_moduleinstallation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='install_date',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_installed',
        ),
        migrations.RemoveField(
            model_name='module',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='module',
            name='version',
        ),
        migrations.RemoveField(
            model_name='moduleinstallation',
            name='status',
        ),
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moduleinstallation',
            name='is_installed',
            field=models.BooleanField(default=False, verbose_name='Is Installed'),
        ),
        migrations.AddField(
            model_name='moduleinstallation',
            name='version',
            field=models.CharField(max_length=20, null=True, verbose_name='Version'),
        ),
        migrations.CreateModel(
            name='ModuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_engine.module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
