# Generated by Django 5.1.10 on 2025-06-06 15:06

from django.db import migrations


def add_admin_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    email = "admin@admin.com"
    if not User.objects.filter(username=email).first():
        User.objects.create_superuser(email, email=email, password="tester1234")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin_user)
    ]
